name: tiksi_avia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    

  flutter_svg: ^1.1.5
  simple_animations: ^5.0.0+2
  supercharged: ^2.1.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.4.0
  firebase_auth: ^3.1.3
  firebase_database: ^9.1.4
  firebase_messaging: ^13.0.2
  firebase_app_check: ^0.0.2+1
  modal_bottom_sheet: ^2.0.0
  http: ^0.13.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.15
  connectivity: ^3.0.6
  provider: ^6.0.1
  after_layout: ^1.1.0
  email_validator: ^2.0.1
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter    
  flutter_native_splash: ^2.2.9
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Light.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
